### ISSUE TITLE
On the problem of simulated current density

### ISSUE THREAD

**Issue by code-whale** [ubermag/micromagneticdata#3]
Dear ubermag team，
I need to add current density related parameters, but I don't know how to write instructions. Please tell me how to solve this problem.

**Comment by marijanbeg** [comment]
Hi @code-whale, can you give us more details? Current density for what? Zhang-Li term?

**Comment by code-whale** [comment]
Yes, I have seen the Zhang-Li term in the program you provided. I think you have replaced the current density J with β, but I would like to ask if the current density parameter can be defined in programming as it is directly assigned to J in oommf and mumax3. Or the current density can only be controlled by controlling the value of β, because I am initially learning the content of micromagnetic simulation. I don't understand the thickness of the free layer in the β formula. I don't understand what part of the thickness he is referring to in a model.
![A3VN{F%{VLINVSZQ(WF`%P4](https://user-images.githubusercontent.com/61874432/85077629-55095400-b1f5-11ea-8ee9-c88a47c38da2.png)

**Comment by marijanbeg** [comment]
I think I understand now. Zhang-Li term (https://micromagneticmodel.readthedocs.io/en/latest/zhangli.html) is actually based on this extension: https://www.zurich.ibm.com/st/nanomagnetism/spintevolve.html, which not defined in terms of J. The term you are looking at is actually Slonczewski term (https://micromagneticmodel.readthedocs.io/en/latest/slonczewski.html) and it is defined in terms of current density J.

**Comment by code-whale** [comment]
Dear Marjian Beg，
Thank you very much for your detailed answer. I think I now know how to set it up. 
I wish you all the best.
